export const workLang = {
    explorer : "EXPLORER",
    back: "Back",
    load: "Creating your workspace, Hang On!",
    toastFolderHeader: "Folder Creation",
    errorFolder: "Please type a name to create a folder!",
    errorFile: "Please type a name to create a file!",
    toastFileHeader: "File Creation",
    preview: "Select a file to view its content",
    reload: "Loading your content!",
    saveReport: "Save Report",
    content: "Automation success, Do you want to save this report?",
    successAlert: "Report saved successfully!",
    errorAlert: "Internal error occured.",
    runningAutomation: "Automation is in progress...",
    savingReport: "Automation completed, saving the report!",
    reportSaved: "Report saved successfully!",
    error: 'Some internal error occured',
    noFiles: "No folders and files",
    setDirectory: "Your project is currently empty!!",
    addFolders: "Add Folders"
}